services:

  mysql_engine:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app_network
      
  express_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    networks:
      - app_network
    command: ["node", "app.js"]

  frontend:
    build:
      context: .
    ports:
      - "81:80"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network

networks:
  app_network:
